set incsearch
set hidden
set noswapfile
set nobackup
set enc=utf-8
set undodir=$HOME/vimfiles/undo

packadd minpac

call minpac#init()

call minpac#add('k-takata/minpac', {'type':'opt'}) 
call minpac#add('easymotion/vim-easymotion')
call minpac#add('tpope/vim-commentary')
call minpac#add('machakann/vim-sandwich')

" filetype
" elm
call minpac#add('ElmCast/elm-vim')

" elixir
call minpac#add('elixir-editors/vim-elixir')
call minpac#add('mhinz/vim-mix-format')


" colorscheme
let g:spring_night_kill_italic=1
call minpac#add('rhysd/vim-color-spring-night')
call minpac#add('dracula/vim')

let g:eskk#large_dictionary = "$HOME\\skk\\SKK-JISYO.L"
call minpac#add('tyru/eskk.vim')

let g:qfixmemo_mapleader = 'gw'
call minpac#add('fuenor/qfixhowm')

let howm_dir             = "$HOME/howm"
let howm_filename        = '%Y/%m/%Y-%m-%d-%H%M%S.txt'
let howm_fileencoding    = 'utf-8'
let howm_fileformat      = 'unix'

packloadall

colorscheme spring-night
